# Generated by Django 4.2.10 on 2024-02-29 08:12

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('menu', '0001_initial'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.collection'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.page'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='menu_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='menu_meta_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemtranslation',
            unique_together={('language_code', 'menu_item')},
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='menuitem_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='menuitem_meta_idx'),
        ),
    ]
