# Generated by Django 4.2.10 on 2024-02-29 08:12

from decimal import Decimal
import djElenor.checkout.models
import djElenor.core.utils.json_serializer
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_change', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_transaction_modified_at', models.DateTimeField(blank=True, null=True)),
                ('automatically_refundable', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, default='')),
                ('currency', models.CharField(max_length=3)),
                ('country', django_countries.fields.CountryField(default=djElenor.checkout.models.get_default_country, max_length=2)),
                ('total_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('total_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('subtotal_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('subtotal_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('shipping_price_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('shipping_price_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('shipping_tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=5)),
                ('authorize_status', models.CharField(choices=[('none', 'The checkout is not authorized'), ('partial', 'The checkout is partially authorized'), ('full', 'The checkout is fully authorized')], db_index=True, default='none', max_length=32)),
                ('charge_status', models.CharField(choices=[('none', 'The checkout is not charged'), ('partial', 'The checkout is partially charged'), ('full', 'The checkout is fully charged'), ('overcharged', 'The checkout is overcharged')], db_index=True, default='none', max_length=32)),
                ('price_expiration', models.DateTimeField(default=django.utils.timezone.now)),
                ('discount_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('discount_name', models.CharField(blank=True, max_length=255, null=True)),
                ('translated_discount_name', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher_code', models.CharField(blank=True, max_length=255, null=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en-us', max_length=35)),
                ('tax_exemption', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-last_change', 'pk'),
                'permissions': (('manage_checkouts', 'Manage checkouts'), ('handle_checkouts', 'Handle checkouts'), ('handle_taxes', 'Handle taxes'), ('manage_taxes', 'Manage taxes')),
            },
        ),
        migrations.CreateModel(
            name='CheckoutMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=djElenor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=djElenor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('checkout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_storage', to='checkout.checkout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckoutLine',
            fields=[
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=djElenor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=djElenor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('old_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_override', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('total_price_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('total_price_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=5)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='checkout.checkout')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'abstract': False,
            },
        ),
    ]
