# Generated by Django 4.2.10 on 2024-02-29 08:12

import djElenor.core.db.fields
import djElenor.core.utils.editorjs
import djElenor.core.utils.json_serializer
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPageAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='AssignedProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='AssignedVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedVariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=djElenor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=djElenor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('product-type', 'Product type'), ('page-type', 'Page type')], max_length=50)),
                ('input_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('multiselect', 'Multi Select'), ('file', 'File'), ('reference', 'Reference'), ('numeric', 'Numeric'), ('rich-text', 'Rich Text'), ('plain-text', 'Plain Text'), ('swatch', 'Swatch'), ('boolean', 'Boolean'), ('date', 'Date'), ('date-time', 'Date Time')], default='dropdown', max_length=50)),
                ('entity_type', models.CharField(blank=True, choices=[('Page', 'Page'), ('Product', 'Product'), ('ProductVariant', 'Product Variant')], max_length=50, null=True)),
                ('unit', models.CharField(blank=True, choices=[('mm', 'mm'), ('cm', 'cm'), ('dm', 'dm'), ('m', 'm'), ('km', 'km'), ('ft', 'ft'), ('yd', 'yd'), ('inch', 'inch'), ('sq_mm', 'sq_mm'), ('sq_cm', 'sq_cm'), ('sq_dm', 'sq_dm'), ('sq_m', 'sq_m'), ('sq_km', 'sq_km'), ('sq_ft', 'sq_ft'), ('sq_yd', 'sq_yd'), ('sq_inch', 'sq_inch'), ('cubic_millimeter', 'cubic_millimeter'), ('cubic_centimeter', 'cubic_centimeter'), ('cubic_decimeter', 'cubic_decimeter'), ('cubic_meter', 'cubic_meter'), ('liter', 'liter'), ('cubic_foot', 'cubic_foot'), ('cubic_inch', 'cubic_inch'), ('cubic_yard', 'cubic_yard'), ('qt', 'qt'), ('pint', 'pint'), ('fl_oz', 'fl_oz'), ('acre_in', 'acre_in'), ('acre_ft', 'acre_ft'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz'), ('kg', 'kg'), ('tonne', 'tonne')], max_length=100, null=True)),
                ('value_required', models.BooleanField(blank=True, default=False)),
                ('is_variant_only', models.BooleanField(blank=True, default=False)),
                ('visible_in_storefront', models.BooleanField(blank=True, default=True)),
                ('filterable_in_storefront', models.BooleanField(blank=True, default=False)),
                ('filterable_in_dashboard', models.BooleanField(blank=True, default=False)),
                ('storefront_search_position', models.IntegerField(blank=True, default=0)),
                ('available_in_grid', models.BooleanField(blank=True, default=False)),
                ('max_sort_order', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('storefront_search_position', 'slug'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='AttributeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='AttributeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rich_text', djElenor.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=djElenor.core.utils.editorjs.clean_editor_js)),
                ('plain_text', models.TextField(blank=True, null=True)),
                ('boolean', models.BooleanField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='AttributeValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=250)),
                ('rich_text', djElenor.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=djElenor.core.utils.editorjs.clean_editor_js)),
                ('plain_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
                ('variant_selection', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
    ]
